### ISSUE TITLE
ReadTimeout

### ISSUE THREAD

**Issue by JordanRN** [napalm-automation-community/napalm-ruckus-fastiron#12]
When connecting to a device, after X number of seconds the connection times out after calling get_facts

```
`(venv) root@netbox2:/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/napalm# python ./fastiron_test.py 
/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
SSH connection established to 192.168.1.38:22
Interactive SSH session established
Traceback (most recent call last):
  File "/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/napalm_ruckus_fastiron/FastIron.py", line 102, in open
    self.device.session_preparation()
  File "/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/netmiko/ruckus/ruckus_fastiron.py", line 15, in session_preparation
    self._test_channel_read()
  File "/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1243, in _test_channel_read
    new_data += self.read_channel_timing(read_timeout=20)
  File "/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 825, in read_channel_timing
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

read_channel_timing's absolute timer expired.

The network device was continually outputting data for longer than 20
seconds.

If this is expected i.e. the command you are executing is continually emitting
data for a long period of time, then you can set 'read_timeout=x' seconds. If
you want Netmiko to keep reading indefinitely (i.e. to only stop when there is
no new data), then you can set 'read_timeout=0'.

You can look at the Netmiko session_log or debug log for more information.



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/napalm/./fastiron_test.py", line 4, in <module>
    driver.open()
  File "/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/napalm_ruckus_fastiron/FastIron.py", line 112, in open
    raise ConnectionException("Cannot connect to switch: %s:%s" % (self.hostname,
napalm.base.exceptions.ConnectionException: Cannot connect to switch: 192.168.1.38:22
(venv) root@netbox2:/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/napalm# ^C
(venv) root@netbox2:/opt/netbox-4.0.8/venv/lib/python3.10/site-packages/napalm# `
```

**Comment by KittyKatt** [comment]
@JordanRN Over a year later, did you ever figure this out? I'm having the same issue through Nautobot with the napalm driver.

**Comment by JordanRN** [comment]
> [@JordanRN](https://github.com/JordanRN) Over a year later, did you ever figure this out? I'm having the same issue through Nautobot with the napalm driver.

I was able to make some of it work... I took parts of Pull Request #11 and #10 to get connections to work... Although some of the get items don't work.

However..... If you're using radius to login, it does not work. You need to use local logins.

**Comment by KittyKatt** [comment]
> > [@JordanRN](https://github.com/JordanRN) Over a year later, did you ever figure this out? I'm having the same issue through Nautobot with the napalm driver.
> 
> I was able to make some of it work... I took parts of Pull Request [#11](https://github.com/napalm-automation-community/napalm-ruckus-fastiron/pull/11) and [#10](https://github.com/napalm-automation-community/napalm-ruckus-fastiron/pull/10) to get connections to work... Although some of the get items don't work.
> 
> However..... If you're using radius to login, it does not work. You need to use local logins.

Awesome, thank you. I'll give this a try.

**Comment by MichaelKetchel** [comment]
I may have fixed this in my branch--it was a secondary call to netmiko's session preparation logic causing it to hang.

https://github.com/MichaelKetchel/napalm-ruckus-fastiron
